#pragma once
#include "wx/wx.h"

class MainFrame : public wxFrame
{
public:
    MainFrame(const wxString& title);

    struct languages {
        wxString* name;
        wxString* code;
    } lang[142] = {
       {(wxString*)"Afrikaans",(wxString*)"af"},
       {(wxString*)"Albanian - shqip",(wxString*)"sq"},
       {(wxString*)"Amharic - አማርኛ",(wxString*)"am"},
       {(wxString*)"Arabic - العربية",(wxString*)"ar"},
       {(wxString*)"Aragonese - aragonés",(wxString*)"an"},
       {(wxString*)"Armenian - հայերեն",(wxString*)"hy"},
       {(wxString*)"Asturian - asturianu",(wxString*)"ast"},
       {(wxString*)"Azerbaijani - azərbaycan dili",(wxString*)"az"},
       {(wxString*)"Basque - euskara",(wxString*)"eu"},
       {(wxString*)"Belarusian - беларуская",(wxString*)"be"},
       {(wxString*)"Bengali - বাংলা",(wxString*)"bn"},
       {(wxString*)"Bosnian - bosanski",(wxString*)"bs"},
       {(wxString*)"Breton - brezhoneg",(wxString*)"br"},
       {(wxString*)"Bulgarian - български",(wxString*)"bg"},
       {(wxString*)"Catalan - català",(wxString*)"ca"},
       {(wxString*)"Central Kurdish - کوردی (دەستنوسی عەرەبی)",(wxString*)"ckb"},
       {(wxString*)"Chinese - 中文",(wxString*)"zh"},
       {(wxString*)"Chinese (Hong Kong) - 中文（香港）",(wxString*)"zh-HK"},
       {(wxString*)"Chinese (Simplified) - 中文（简体）",(wxString*)"zh-CN"},
       {(wxString*)"Chinese (Traditional) - 中文（繁體）",(wxString*)"zh-TW"},
       {(wxString*)"Corsican",(wxString*)"co"},
       {(wxString*)"Croatian - hrvatski",(wxString*)"hr"},
       {(wxString*)"Czech - čeština",(wxString*)"cs"},
       {(wxString*)"Danish - dansk",(wxString*)"da"},
       {(wxString*)"Dutch - Nederlands",(wxString*)"nl"},
       {(wxString*)"English",(wxString*)"en"},
       {(wxString*)"English (Australia)",(wxString*)"en-AU"},
       {(wxString*)"English (Canada)",(wxString*)"en-CA"},
       {(wxString*)"English (India)",(wxString*)"en-IN"},
       {(wxString*)"English (New Zealand)",(wxString*)"en-NZ"},
       {(wxString*)"English (South Africa)",(wxString*)"en-ZA"},
       {(wxString*)"English (United Kingdom)",(wxString*)"en-GB"},
       {(wxString*)"English (United States)",(wxString*)"en-US"},
       {(wxString*)"Esperanto - esperanto",(wxString*)"eo"},
       {(wxString*)"Estonian - eesti",(wxString*)"et"},
       {(wxString*)"Faroese - føroyskt",(wxString*)"fo"},
       {(wxString*)"Filipino",(wxString*)"fil"},
       {(wxString*)"Finnish - suomi",(wxString*)"fi"},
       {(wxString*)"French - français",(wxString*)"fr"},
       {(wxString*)"French (Canada) - français (Canada)",(wxString*)"fr-CA"},
       {(wxString*)"French (France) - français (France)",(wxString*)"fr-FR"},
       {(wxString*)"French (Switzerland) - français (Suisse)",(wxString*)"fr-CH"},
       {(wxString*)"Galician - galego",(wxString*)"gl"},
       {(wxString*)"Georgian - ქართული",(wxString*)"ka"},
       {(wxString*)"German - Deutsch",(wxString*)"de"},
       {(wxString*)"German (Austria) - Deutsch (Österreich)",(wxString*)"de-AT"},
       {(wxString*)"German (Germany) - Deutsch (Deutschland)",(wxString*)"de-DE"},
       {(wxString*)"German (Liechtenstein) - Deutsch (Liechtenstein)",(wxString*)"de-LI"},
       {(wxString*)"German (Switzerland) - Deutsch (Schweiz)",(wxString*)"de-CH"},
       {(wxString*)"Greek - Ελληνικά",(wxString*)"el"},
       {(wxString*)"Guarani",(wxString*)"gn"},
       {(wxString*)"Gujarati - ગુજરાતી",(wxString*)"gu"},
       {(wxString*)"Hausa",(wxString*)"ha"},
       {(wxString*)"Hawaiian - ʻŌlelo Hawaiʻi",(wxString*)"haw"},
       {(wxString*)"Hebrew - עברית",(wxString*)"he"},
       {(wxString*)"Hindi - हिन्दी",(wxString*)"hi"},
       {(wxString*)"Hungarian - magyar",(wxString*)"hu"},
       {(wxString*)"Icelandic - íslenska",(wxString*)"is"},
       {(wxString*)"Indonesian - Indonesia",(wxString*)"id"},
       {(wxString*)"Interlingua",(wxString*)"ia"},
       {(wxString*)"Irish - Gaeilge",(wxString*)"ga"},
       {(wxString*)"Italian - italiano",(wxString*)"it"},
       {(wxString*)"Italian (Italy) - italiano (Italia)",(wxString*)"it-IT"},
       {(wxString*)"Italian (Switzerland) - italiano (Svizzera)",(wxString*)"it-CH"},
       {(wxString*)"Japanese - 日本語",(wxString*)"ja"},
       {(wxString*)"Kannada - ಕನ್ನಡ",(wxString*)"kn"},
       {(wxString*)"Kazakh - қазақ тілі",(wxString*)"kk"},
       {(wxString*)"Khmer - ខ្មែរ",(wxString*)"km"},
       {(wxString*)"Korean - 한국어",(wxString*)"ko"},
       {(wxString*)"Kurdish - Kurdî",(wxString*)"ku"},
       {(wxString*)"Kyrgyz - кыргызча",(wxString*)"ky"},
       {(wxString*)"Lao - ລາວ",(wxString*)"lo"},
       {(wxString*)"Latin",(wxString*)"la"},
       {(wxString*)"Latvian - latviešu",(wxString*)"lv"},
       {(wxString*)"Lingala - lingála",(wxString*)"ln"},
       {(wxString*)"Lithuanian - lietuvių",(wxString*)"lt"},
       {(wxString*)"Macedonian - македонски",(wxString*)"mk"},
       {(wxString*)"Malay - Bahasa Melayu",(wxString*)"ms"},
       {(wxString*)"Malayalam - മലയാളം",(wxString*)"ml"},
       {(wxString*)"Maltese - Malti",(wxString*)"mt"},
       {(wxString*)"Marathi - मराठी",(wxString*)"mr"},
       {(wxString*)"Mongolian - монгол",(wxString*)"mn"},
       {(wxString*)"Nepali - नेपाली",(wxString*)"ne"},
       {(wxString*)"Norwegian - norsk",(wxString*)"no"},
       {(wxString*)"Norwegian Bokmål - norsk bokmål",(wxString*)"nb"},
       {(wxString*)"Norwegian Nynorsk - nynorsk",(wxString*)"nn"},
       {(wxString*)"Occitan",(wxString*)"oc"},
       {(wxString*)"Oriya - ଓଡ଼ିଆ",(wxString*)"or"},
       {(wxString*)"Oromo - Oromoo",(wxString*)"om"},
       {(wxString*)"Pashto - پښتو",(wxString*)"ps"},
       {(wxString*)"Persian - فارسی",(wxString*)"fa"},
       {(wxString*)"Polish - polski",(wxString*)"pl"},
       {(wxString*)"Portuguese - português",(wxString*)"pt"},
       {(wxString*)"Portuguese (Brazil) - português (Brasil)",(wxString*)"pt-BR"},
       {(wxString*)"Portuguese (Portugal) - português (Portugal)",(wxString*)"pt-PT"},
       {(wxString*)"Punjabi - ਪੰਜਾਬੀ",(wxString*)"pa"},
       {(wxString*)"Quechua",(wxString*)"qu"},
       {(wxString*)"Romanian - română",(wxString*)"ro"},
       {(wxString*)"Romanian (Moldova) - română (Moldova)",(wxString*)"mo"},
       {(wxString*)"Romansh - rumantsch",(wxString*)"rm"},
       {(wxString*)"Russian - русский",(wxString*)"ru"},
       {(wxString*)"Scottish Gaelic",(wxString*)"gd"},
       {(wxString*)"Serbian - српски",(wxString*)"sr"},
       {(wxString*)"Serbo - Croatian",(wxString*)"sh"},
       {(wxString*)"Shona - chiShona",(wxString*)"sn"},
       {(wxString*)"Sindhi",(wxString*)"sd"},
       {(wxString*)"Sinhala - සිංහල",(wxString*)"si"},
       {(wxString*)"Slovak - slovenčina",(wxString*)"sk"},
       {(wxString*)"Slovenian - slovenščina",(wxString*)"sl"},
       {(wxString*)"Somali - Soomaali",(wxString*)"so"},
       {(wxString*)"Southern Sotho",(wxString*)"st"},
       {(wxString*)"Spanish - español",(wxString*)"es"},
       {(wxString*)"Spanish (Argentina) - español (Argentina)",(wxString*)"es-AR"},
       {(wxString*)"Spanish (Latin America) - español (Latinoamérica)",(wxString*)"es-419"},
       {(wxString*)"Spanish (Mexico) - español (México)",(wxString*)"es-MX"},
       {(wxString*)"Spanish (Spain) - español (España)",(wxString*)"es-ES"},
       {(wxString*)"Spanish (United States) - español (Estados Unidos)",(wxString*)"es-US"},
       {(wxString*)"Sundanese",(wxString*)"su"},
       {(wxString*)"Swahili - Kiswahili",(wxString*)"sw"},
       {(wxString*)"Swedish - svenska",(wxString*)"sv"},
       {(wxString*)"Tajik - тоҷикӣ",(wxString*)"tg"},
       {(wxString*)"Tamil - தமிழ்",(wxString*)"ta"},
       {(wxString*)"Tatar",(wxString*)"tt"},
       {(wxString*)"Telugu - తెలుగు",(wxString*)"te"},
       {(wxString*)"Thai - ไทย",(wxString*)"th"},
       {(wxString*)"Tigrinya - ትግርኛ",(wxString*)"ti"},
       {(wxString*)"Tongan - lea fakatonga",(wxString*)"to"},
       {(wxString*)"Turkish - Türkçe",(wxString*)"tr"},
       {(wxString*)"Turkmen",(wxString*)"tk"},
       {(wxString*)"Twi",(wxString*)"tw"},
       {(wxString*)"Ukrainian - українська",(wxString*)"uk"},
       {(wxString*)"Urdu - اردو",(wxString*)"ur"},
       {(wxString*)"Uyghur",(wxString*)"ug"},
       {(wxString*)"Uzbek - o‘zbek",(wxString*)"uz"},
       {(wxString*)"Viet(wxString*) - Tiếng Việt",(wxString*)"vi"},
       {(wxString*)"Walloon - wa",(wxString*)"wa"},
       {(wxString*)"Welsh - Cymraeg",(wxString*)"cy"},
       {(wxString*)"Western Frisian",(wxString*)"fy"},
       {(wxString*)"Xhosa",(wxString*)"xh"},
       {(wxString*)"Yiddish",(wxString*)"yi"},
       {(wxString*)"Yoruba - Èdè Yorùbá",(wxString*)"yo"},
       {(wxString*)"Zulu - isiZulu",(wxString*)"zu"}
    };

    wxArrayString languageArray = {"Afrikaans", "Albanian", "Amharic", "Arabic", "Aragonese", "Armenian", "Asturian", "Azerbaijani", "Basque", "Belarusian", "Bengali", "Bosnian", "Breton", "Bulgarian", "Catalan", "Central Kurdish", "Chinese", "Chinese (Hong Kong)", "Chinese (Simplified)", "Chinese (Traditional)", "Corsican", "Croatian", "Czech", "Danish", "Dutch", "English", "English (Australia)", "English (Canada)", "English (India)", "English (New Zealand)", "English (South Africa)", "English (United Kingdom)", "English (United States)", "Esperanto", "Estonian", "Faroese", "Filipino", "Finnish", "French", "French (Canada)", "French (France)", "French (Switzerland)", "Galician", "Georgian", "German", "German (Austria)", "German (Germany)", "German (Liechtenstein)", "German (Switzerland)", "Greek", "Guarani", "Gujarati", "Hausa", "Hawaiian", "Hebrew", "Hindi", "Hungarian", "Icelandic", "Indonesian", "Interlingua", "Irish", "Italian", "Italian (Italy)", "Italian (Switzerland)", "Japanese", "Kannada", "Kazakh", "Khmer", "Korean", "Kurdish", "Kyrgyz", "Lao", "Latin", "Latvian", "Lingala", "Lithuanian", "Macedonian", "Malay", "Malayalam", "Maltese", "Marathi", "Mongolian", "Nepali", "Norwegian", "Norwegian Bokmål", "Norwegian Nynorsk", "Occitan", "Oriya", "Oromo", "Pashto", "Persian", "Polish", "Portuguese", "Portuguese (Brazil)", "Portuguese (Portugal)", "Punjabi", "Quechua", "Romanian", "Romanian (Moldova)", "Romansh", "Russian", "Scottish Gaelic", "Serbian", "Serbo", "Shona", "Sindhi", "Sinhala", "Slovak", "Slovenian", "Somali", "Southern Sotho", "Spanish", "Spanish (Argentina)", "Spanish (Latin America)", "Spanish (Mexico)", "Spanish (Spain)", "Spanish (United States)", "Sundanese", "Swahili", "Swedish", "Tajik", "Tamil", "Tatar", "Telugu", "Thai", "Tigrinya", "Tongan", "Turkish", "Turkmen", "Twi", "Ukrainian", "Urdu", "Uyghur", "Uzbek", "Vietnamese", "Walloon", "Welsh", "Western Frisian", "Xhosa", "Yiddish", "Yoruba", "Zulu"};
};

